server:
  port: 8888

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost/mybatis?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456


mybatis:
  type-handlers-package: cn.kj120.study.mybatis.handler
  type-aliases-package: cn.kj120.study.mybatis.domain
  mapper-locations:
    - classpath:mapper/*.xml




